#!/bin/bash

set -e

read -p "Are you sure you want to reset the application? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

APP_ID=com.github.avojak.replay
GSETTINGS_ID=$APP_ID
GSETTINGS_PATH=$APP_ID

print_setting () {
    echo -e "  $1 = $(flatpak run --command=gsettings $GSETTINGS_ID get $GSETTINGS_PATH $1)"
}

set_setting () {
    flatpak run --command=gsettings $GSETTINGS_ID set $GSETTINGS_PATH $1 "$2"
    print_setting $1
}

echo
echo "Resetting GSettings..."

set_setting pos-x 360
set_setting pos-y 360
set_setting window-width 1000
set_setting window-height 600
set_setting emu-pos-x 360
set_setting emu-pos-y 360
set_setting emu-window-width 500
set_setting emu-window-height 500
set_setting user-core-directory ""
set_setting user-rom-directory ""
set_setting handle-window-focus-change true

echo
echo -e "\033[1;32mDone\033[0m"
echo