#!/bin/bash

set -e

read -p "Are you sure you want to reset the application? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

APP_ID=com.github.avojak.replay
GSETTINGS_PATH=$APP_ID

print_setting () {
    echo -e "  $1 = $(flatpak run --command=gsettings $APP_ID get $GSETTINGS_PATH $1)"
}

set_setting () {
    flatpak run --command=gsettings $APP_ID set $GSETTINGS_PATH $1 "$2"
    print_setting $1
}

echo
echo "Resetting GSettings…"

set_setting pos-x 360
set_setting pos-y 360
set_setting window-width 1000
set_setting window-height 600
set_setting emu-pos-x 360
set_setting emu-pos-y 360
set_setting emu-window-width 500
set_setting emu-window-height 500
set_setting emu-window-fullscreen false
set_setting emu-boot-bios false
set_setting emu-default-filter "SHARP"
set_setting user-rom-directory ""
set_setting user-save-directory ""
set_setting download-boxart true
set_setting handle-window-focus-change true

echo
echo "Deleting art cache…"

flatpak run --command=rm $APP_ID -rf /var/config/libretro_art

echo
echo -e "\033[1;32mDone\033[0m"
echo